"""Cypher Combiner — merges chain plan steps into compound Cypher queries.

Single-pass design:

  Phase 1 — Filter chain (nodes only):
    MATCH clauses connected by ``WITH <all_node_vars> LIMIT N``.
    Relationship variables are NOT carried — they would create binding
    constraints that cause Neo4j to return empty results.

  Phase 2 — Edge recovery:
    One re-MATCH per hop with ``WITH ... LIMIT`` between each, using fresh
    relationship variable names.  Each re-MATCH adds one edge variable while
    carrying all previously collected variables forward.

  Example (3-step chain: SNP→Disease, SNP→Gene, Gene→GO):

    MATCH (s:snp)-[r1:part_of_GWAS_signal]->(d:disease) WHERE d.name = "type 1 diabetes"
    WITH s, d LIMIT 50
    MATCH (s)-[r2:part_of_QTL_signal]->(g:gene)
    WITH s, d, g LIMIT 50
    MATCH (g)-[r3:function_annotation]->(fo:gene_ontology)
    WITH s, d, g, fo LIMIT 200
    MATCH (s)-[r4:part_of_GWAS_signal]->(d)
    WITH s, d, g, fo, r4 LIMIT 200
    MATCH (s)-[r5:part_of_QTL_signal]->(g)
    WITH s, d, g, fo, r4, r5 LIMIT 200
    MATCH (g)-[r6:function_annotation]->(fo)
    WITH collect(DISTINCT s)+collect(DISTINCT d)+collect(DISTINCT g)+collect(DISTINCT fo) AS nodes,
         collect(DISTINCT r4)+collect(DISTINCT r5)+collect(DISTINCT r6) AS edges
    RETURN nodes, edges
"""

from __future__ import annotations

import re
from typing import Optional


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _extract_match_only(cypher: str) -> str:
    """Extract only the MATCH ... WHERE ... portion from a Cypher query."""
    lines = cypher.strip().rstrip(";").strip().split("\n")
    match_lines = []
    for line in lines:
        stripped = line.strip()
        if re.match(r'^(WITH|RETURN|LIMIT|ORDER)\b', stripped, re.IGNORECASE):
            break
        match_lines.append(line)
    return "\n".join(match_lines).strip()


def _extract_node_vars(match_clause: str) -> list[str]:
    """Return node variable names from a MATCH clause, in order of appearance."""
    return re.findall(r'\((\w+)(?::\w+)?[^)]*\)', match_clause)


def _extract_rel_vars(match_clause: str) -> list[str]:
    """Return relationship variable names from a MATCH clause."""
    return re.findall(r'\[(\w+):\w+[^\]]*\]', match_clause)


def _rename_rel_var(cypher: str, old_name: str, new_name: str) -> str:
    """Rename a relationship variable in bracket notation: [old:TYPE] → [new:TYPE]."""
    if old_name == new_name:
        return cypher
    return re.sub(
        r'\[' + re.escape(old_name) + r'(:\w+)',
        f'[{new_name}\\1',
        cypher,
    )


def _rename_node_var(cypher: str, old_name: str, new_name: str) -> str:
    """Rename a node variable throughout a MATCH clause."""
    if old_name == new_name:
        return cypher
    cypher = re.sub(
        r'\(' + re.escape(old_name) + r'((?::\w+)?(?:\s*\{[^}]*\})?)\)',
        f'({new_name}\\1)',
        cypher,
    )
    cypher = re.sub(
        r'\b' + re.escape(old_name) + r'\.',
        f'{new_name}.',
        cypher,
    )
    return cypher


def _unbind_node_label(cypher: str, var_name: str) -> str:
    """Remove the label from an already-bound node variable.

    ``(o:OCR)`` → ``(o)``  when `var_name` is ``o``.
    """
    return re.sub(
        r'\(' + re.escape(var_name) + r':\w+(\s*\{[^}]*\})?\)',
        lambda m: f'({var_name}{m.group(1) or ""})',
        cypher,
    )


def _find_join_candidate(node_vars: list[str], prev_join_var: str) -> Optional[str]:
    """Find which node variable should be renamed to match prev_join_var."""
    if prev_join_var in node_vars:
        return None
    for nv in node_vars:
        if nv.startswith(prev_join_var) and nv != prev_join_var:
            return nv
    return node_vars[0] if node_vars else None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def combine_chain(steps: list[dict], limit: int = 50) -> str:
    """Combine chain steps into a single compound Cypher query.

    Each *step* dict must have:
        - ``cypher``  : the individual Cypher query generated by text2cypher
        - ``join_var``: the variable name shared with the *next* step (or None
                        for the last step)

    Returns a single executable Cypher string.
    """
    if not steps:
        return ""

    rel_counter = 0
    lines: list[str] = []
    all_node_vars: list[str] = []       # accumulated across all steps
    all_join_vars: list[str] = []
    renamed_clauses: list[str] = []     # saved for Phase 2 re-MATCH
    bound_node_vars: set[str] = set()

    # ------------------------------------------------------------------
    # Phase 1 — Filter chain: carry all node vars, drop relationship vars
    # ------------------------------------------------------------------
    for idx, step in enumerate(steps):
        raw_cypher = step["cypher"]
        join_var = step.get("join_var")

        match_clause = _extract_match_only(raw_cypher)

        # Rename relationship variables to be globally unique
        for old_rel in _extract_rel_vars(match_clause):
            rel_counter += 1
            match_clause = _rename_rel_var(match_clause, old_rel, f"r{rel_counter}")

        # Rename node vars to match previous step's join_var
        if idx > 0 and all_join_vars:
            prev_join = all_join_vars[-1]
            node_vars_in_step = _extract_node_vars(match_clause)
            if prev_join not in node_vars_in_step:
                candidate = _find_join_candidate(node_vars_in_step, prev_join)
                if candidate:
                    match_clause = _rename_node_var(match_clause, candidate, prev_join)

        # Remove labels from already-bound node variables
        for nv in _extract_node_vars(match_clause):
            if nv in bound_node_vars:
                match_clause = _unbind_node_label(match_clause, nv)

        # Track node vars
        for nv in _extract_node_vars(match_clause):
            bound_node_vars.add(nv)
            if nv not in all_node_vars:
                all_node_vars.append(nv)

        if join_var:
            all_join_vars.append(join_var)

        renamed_clauses.append(match_clause)
        lines.append(match_clause)

        # WITH <all_node_vars> LIMIT N  (after every step including the last)
        is_last = (idx == len(steps) - 1)
        carry_limit = limit * 4 if is_last else limit
        with_clause = f"WITH {', '.join(all_node_vars)} LIMIT {carry_limit}"
        lines.append(with_clause)

    # ------------------------------------------------------------------
    # Phase 2 — Edge recovery: re-MATCH each hop to get relationship vars
    # ------------------------------------------------------------------
    p2_rel_vars: list[str] = []
    p2_bound: set[str] = set(all_node_vars)

    for clause in renamed_clauses:
        rematch = clause

        # Fresh relationship variable names
        for old_rel in _extract_rel_vars(rematch):
            rel_counter += 1
            new_rel = f"r{rel_counter}"
            rematch = _rename_rel_var(rematch, old_rel, new_rel)

        # Strip labels from bound nodes
        for nv in _extract_node_vars(rematch):
            if nv in p2_bound:
                rematch = _unbind_node_label(rematch, nv)
            p2_bound.add(nv)

        new_rels = _extract_rel_vars(rematch)
        p2_rel_vars.extend(new_rels)

        lines.append(rematch)

        # WITH <all_node_vars> + <accumulated_rel_vars> LIMIT N
        carry_vars = all_node_vars + p2_rel_vars
        lines.append(f"WITH {', '.join(carry_vars)} LIMIT {limit * 4}")

    # ------------------------------------------------------------------
    # Replace the last WITH...LIMIT with the final collect + RETURN
    # ------------------------------------------------------------------
    lines.pop()  # remove the last WITH...LIMIT

    node_collects = " + ".join(f"collect(DISTINCT {v})" for v in all_node_vars)
    edge_collects = " + ".join(f"collect(DISTINCT {v})" for v in p2_rel_vars)

    if all_node_vars and p2_rel_vars:
        lines.append(
            f"WITH {node_collects} AS nodes,\n"
            f"     {edge_collects} AS edges"
        )
        lines.append("RETURN nodes, edges")
    elif all_node_vars:
        lines.append(f"WITH {node_collects} AS nodes")
        lines.append("RETURN nodes")
    else:
        lines.append("RETURN *")

    return "\n".join(lines)


def build_executable_queries(plan: dict) -> list[str]:
    """Convert a full plan JSON into a list of executable Cypher strings.

    Steps with ``"source": "hpap"`` are skipped — they are handled separately
    by the HPAP NL-to-SQL pipeline.

    For ``chain`` plans the KG steps are combined into a single compound query.
    For ``parallel`` plans each KG step's Cypher is kept as-is.
    """
    plan_type = plan.get("plan_type", "parallel")
    steps = plan.get("steps", [])

    kg_steps = [s for s in steps if s.get("source") != "hpap"]

    if not kg_steps:
        return []

    if plan_type == "chain":
        compound = combine_chain(kg_steps, limit=50)
        return [compound] if compound else []
    else:
        return [s.get("cypher", "").strip() for s in kg_steps if s.get("cypher", "").strip()]
