"""Build a local, inspectable comparison from frozen benchmark artifacts."""
import argparse,html,json,statistics,hashlib
from workflow57 import evaluate
from pathlib import Path

def main():
 p=argparse.ArgumentParser();p.add_argument('root',type=Path);p.add_argument('--fixture',type=Path,required=True);args=p.parse_args()
 base=args.root;run=base/'run1';fixture=json.loads(args.fixture.read_text());summary=json.loads((run/'summary.json').read_text());rows=[json.loads(l) for l in (run/'report.jsonl').read_text().splitlines()];by={(r['case'],r['arm']):r for r in rows}
 esc=lambda s:html.escape(str(s))
 cards=[];reviews=[]
 notes_path=base/'manual-findings.json';notes=json.loads(notes_path.read_text()).get('notes',{}) if notes_path.exists() else {}
 for c in fixture['cases']:
  key=c['id'];judge=base/'gpt-review'/(key+'.json');j=json.loads(judge.read_text()) if judge.exists() else {};assessments={arm:j.get('assessment',{}).get(label,{}) for label,arm in j.get('label_mapping',{}).items()}
  sections=[]
  for arm in ['original','candidate']:
   row=by.get((key,arm),{});path=run/arm/(key+'.json');artifact=json.loads(path.read_text()) if path.exists() else {};r=artifact.get('run',{});frozen=row.get('evaluation',{});ev=evaluate(c,r) if row else {};judge_note=assessments.get(arm,{})
   reason=(ev.get('error') or {}).get('category') or row.get('harness_error') or ('required graph evidence incomplete' if not ev.get('verified_core_covered') else 'core evidence present; inspect answer quality')
   if key in ['Q17','Q57']:reason='Reference gap; review scope or clarification'
   if key in ['Q52','Q55']:reason='Verified-empty target requires executed-evidence review'
   record={'case':key,'arm':arm,'question':c['question'],'core_covered':ev.get('core_covered'),'verified_core_covered':ev.get('verified_core_covered'),'frozen_core_covered':frozen.get('core_covered'),'atomic_core_covered':ev.get('atomic_coverage',{}).get('core_covered'),'reason':reason,'advisory_review':judge_note,'manual_finding':notes.get(key),'status':row.get('status'),'has_answer':bool(r.get('graph_answer')),'missing_nodes':ev.get('missing_nodes',[]),'missing_edges':ev.get('missing_edges',[]),'cost_usd':row.get('accounting',{}).get('settled_cost_usd'),'first_preview_s':row.get('first_preview_s'),'settled_preview_s':row.get('settled_preview_s')};reviews.append(record)
   metrics=' · '.join([f"Verified core: {ev.get('verified_core_covered','pending')} · raw core: {ev.get('core_covered','pending')} (frozen: {frozen.get('core_covered','pending')})",f"First: {row.get('first_preview_s',0) or 0:.2f}s",f"Settled: {row.get('settled_preview_s',0) or 0:.2f}s",f"Cost: ${row.get('accounting',{}).get('settled_cost_usd',0):.4f}"])
   quality=json.dumps(judge_note,indent=2,ensure_ascii=False)
   sections.append(f'<section><h3>{esc(arm)}</h3><p>{esc(metrics)}</p><p>{esc(reason)}</p><details><summary>Core and optional evidence coverage</summary><pre>{esc(json.dumps(ev,indent=2,ensure_ascii=False))}</pre></details><details open><summary>Advisory quality review (GPT; not final acceptance)</summary><pre>{esc(quality)}</pre></details><h4>Actual answer</h4><pre>{esc(r.get("graph_answer") or "No answer produced")}</pre></section>')
  cards.append(f'<details class="case"><summary>{esc(key)} — {esc(c["question"])}</summary><p>{esc(notes.get(key,''))}</p><details><summary>Reviewed core / extra reference</summary><pre>{esc(json.dumps({'core':c['core'],'extra':c['extra']},indent=2,ensure_ascii=False))}</pre></details><div class="pair">{"".join(sections)}</div></details>')
 doc='''<!doctype html><html><meta charset="utf-8"><title>PanKagent 57-question comparison</title><style>body{font:15px system-ui;margin:30px;max-width:1600px;background:#f5f6fa;color:#182536}h1{margin-bottom:8px}input{padding:12px;width:70%;margin:20px 0;border:1px solid #abb7c8;border-radius:7px}.case{background:white;padding:15px;margin:10px 0;border:1px solid #ccd5df;border-radius:8px}summary{cursor:pointer;font-weight:600}.pair{display:grid;grid-template-columns:1fr 1fr;gap:24px}section{min-width:0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.6 ui-monospace}section>p{color:#47566b}details details{margin:12px 0;border-top:1px solid #ddd;padding-top:10px}@media(max-width:850px){.pair{grid-template-columns:1fr}}</style><h1>PanKagent: original vs competing candidates</h1><p>Same Claude model, isolated backends, fixed reviewed fixture. Core retrieval is separate from scientific correctness. Extra relevant evidence is allowed. GPT review is advisory and blind to arm identity.</p>'''
 final_path=base/'final-summary.json'
 if final_path.exists():
  final=json.loads(final_path.read_text());a=final['arms']['original'];b=final['arms']['candidate'];lat=final['matched_success_latency']
  overview=[('Verified core or correct empty result',str(a['verified_core_or_verified_empty'])+'/57',str(b['verified_core_or_verified_empty'])+'/57'),('First preview, paired median',f"{lat['first_preview_s']['original']:.2f} s",f"{lat['first_preview_s']['candidate']:.2f} s"),('Settled preview, paired median',f"{lat['settled_preview_s']['original']:.2f} s",f"{lat['settled_preview_s']['candidate']:.2f} s"),('Mean API cost / attempt',f"${a['mean_cost_per_attempt_usd']:.4f}",f"${b['mean_cost_per_attempt_usd']:.4f}")]
  doc+='<h2>Completed comparison</h2><p>Keep the original default for now. Neither reaches 80% core coverage. Core coverage is not a claim that every sentence is correct.</p><table cellpadding="10"><tr><th>Measure</th><th>Original</th><th>Competing candidates</th></tr>'+''.join('<tr>'+''.join('<td>'+esc(v)+'</td>' for v in row)+'</tr>' for row in overview)+'</table><p>False conflict confirmed in Q49: identical sample membership, different optional anatomy annotations. See REPORT.md for findings and disclosed reference refinements.</p>'
 doc+='<p>Offline core refinement: Q13–Q16: optional coloc lead-membership edges moved to extras. Q42/Q44/Q45: optional cell/disease context moved to extras for broad gene introductions. Both arms were rescored equally, without rerunning. Frozen scores are preserved below.</p>'
 doc+=f'<p>{len(rows)} / 114 attempts recorded. No dev activation.</p><details><summary>Timing, accounting and denominators</summary><pre>{esc(json.dumps(summary,indent=2))}</pre></details><input id="search" placeholder="Filter by Q number, gene, topic, error, or answer text"><main>'+''.join(cards)+'</main><script>document.querySelector("#search").addEventListener("input",e=>{let q=e.target.value.toLowerCase();document.querySelectorAll(".case").forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(q))})</script></html>'
 (base/'comparison.html').write_text(doc);(base/'case-reviews.json').write_text(json.dumps(reviews,indent=2,ensure_ascii=False)+'\n')
 (base/'rescored-summary.json').write_text(json.dumps({'fixture_sha256':hashlib.sha256(args.fixture.read_bytes()).hexdigest(),'frozen_fixture_sha256':json.loads((run/'workflow57-runner-manifest.json').read_text()).get('review_fixture_sha256'),'arms':{arm:{'attempted':len([r for r in reviews if r['arm']==arm and r['status'] is not None]),'core_covered':sum(bool(r['core_covered']) for r in reviews if r['arm']==arm),'frozen_core_covered':sum(bool(r['frozen_core_covered']) for r in reviews if r['arm']==arm)} for arm in ['original','candidate']}},indent=2)+'\n')
 print(json.dumps({'attempts':len(rows),'report':str(base/'comparison.html')}))
if __name__=='__main__':main()
