"""
Prompt Hints Manager for Deep Think Mode.

Manages hints/warnings generated by Deep Think analysis that are injected
into Cypher Generator and Orchestrator prompts. Hints accumulate across
iterations and persist to a JSON file.

Features:
- Load/save hints from/to JSON file
- Accumulate hints across training iterations
- Deduplication to avoid repeating identical hints
- Max 5 hints per agent/role (oldest dropped when exceeded)
- Clear mechanism for resetting hints
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# Maximum hints per agent/role to prevent prompt bloat
MAX_HINTS_PER_AGENT = 10


class PromptHintsManager:
    """
    Manages Deep Think prompt hints for Cypher Generator and Orchestrator.
    
    Hints are organized as:
    {
        "last_updated": "ISO timestamp",
        "last_iteration": int,
        "cypher_generator": [
            {"text": "...", "severity": "critical|warning|info", "added_iteration": int}
        ],
        "orchestrator": {
            "generation": [...],
            "data_eval": [...],
            "synthesis": [...],
            "answer_eval": [...]
        }
    }
    """
    
    VALID_SEVERITIES = ['critical', 'warning', 'info']
    ORCHESTRATOR_ROLES = ['generation', 'data_eval', 'synthesis', 'answer_eval']
    
    def __init__(self, hints_file: str):
        """
        Initialize the PromptHintsManager.
        
        Args:
            hints_file: Path to the JSON file for persisting hints
        """
        self.hints_file = Path(hints_file)
        self._hints: Dict[str, Any] = self._empty_hints()
        
        # Load existing hints if file exists
        if self.hints_file.exists():
            self.load_hints()
        
        logger.debug(f"PromptHintsManager initialized with file: {hints_file}")
    
    def _empty_hints(self) -> Dict[str, Any]:
        """Return empty hints structure."""
        return {
            "last_updated": None,
            "last_iteration": 0,
            "cypher_generator": [],
            "orchestrator": {
                "generation": [],
                "data_eval": [],
                "synthesis": [],
                "answer_eval": []
            }
        }
    
    def load_hints(self) -> Dict[str, Any]:
        """
        Load hints from file.
        
        Returns:
            Loaded hints dict, or empty hints if file doesn't exist or is corrupted
        """
        if not self.hints_file.exists():
            logger.debug(f"Hints file not found: {self.hints_file}")
            self._hints = self._empty_hints()
            return self._hints
        
        try:
            with open(self.hints_file, 'r') as f:
                data = json.load(f)
            
            # Validate structure
            if not isinstance(data, dict):
                raise ValueError("Hints file is not a dict")
            
            # Ensure all required keys exist
            self._hints = self._empty_hints()
            self._hints["last_updated"] = data.get("last_updated")
            self._hints["last_iteration"] = data.get("last_iteration", 0)
            
            # Load cypher_generator hints
            if "cypher_generator" in data and isinstance(data["cypher_generator"], list):
                self._hints["cypher_generator"] = data["cypher_generator"]
            
            # Load orchestrator hints
            if "orchestrator" in data and isinstance(data["orchestrator"], dict):
                for role in self.ORCHESTRATOR_ROLES:
                    if role in data["orchestrator"] and isinstance(data["orchestrator"][role], list):
                        self._hints["orchestrator"][role] = data["orchestrator"][role]
            
            logger.info(f"Loaded hints from {self.hints_file}")
            return self._hints
            
        except (json.JSONDecodeError, ValueError) as e:
            logger.warning(f"Failed to load hints file (corrupted?): {e}")
            self._hints = self._empty_hints()
            return self._hints
    
    def save_hints(self):
        """Save current hints to file."""
        self._hints["last_updated"] = datetime.now().isoformat()
        
        # Ensure parent directory exists
        self.hints_file.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            with open(self.hints_file, 'w') as f:
                json.dump(self._hints, f, indent=2)
            logger.info(f"Saved hints to {self.hints_file}")
        except Exception as e:
            logger.error(f"Failed to save hints: {e}")
    
    def add_hints(self, new_hints: Dict[str, Any], iteration: int):
        """
        Add new hints from Deep Think analysis.
        
        Handles deduplication and max limit enforcement.
        
        Args:
            new_hints: Dict with 'cypher_generator' and/or 'orchestrator' hints
            iteration: Current training iteration number
            
        Expected format:
        {
            "cypher_generator": [
                {"text": "...", "severity": "warning"}
            ],
            "orchestrator": {
                "generation": [...],
                "synthesis": [...]
            }
        }
        """
        self._hints["last_iteration"] = iteration
        
        # Add cypher_generator hints
        if "cypher_generator" in new_hints:
            cg_hints = new_hints["cypher_generator"]
            if isinstance(cg_hints, list):
                for hint in cg_hints:
                    self._add_single_hint(
                        self._hints["cypher_generator"],
                        hint,
                        iteration
                    )
        
        # Add orchestrator hints
        if "orchestrator" in new_hints:
            orch_hints = new_hints["orchestrator"]
            if isinstance(orch_hints, dict):
                for role in self.ORCHESTRATOR_ROLES:
                    if role in orch_hints and isinstance(orch_hints[role], list):
                        for hint in orch_hints[role]:
                            self._add_single_hint(
                                self._hints["orchestrator"][role],
                                hint,
                                iteration
                            )
        
        # Save after adding
        self.save_hints()
        
        logger.info(f"Added hints at iteration {iteration}")
    
    def _add_single_hint(
        self,
        hint_list: List[Dict[str, Any]],
        hint: Dict[str, Any],
        iteration: int
    ):
        """
        Add a single hint to a hint list with deduplication and limit enforcement.
        
        Args:
            hint_list: List to add hint to
            hint: Hint dict with 'text' and optionally 'severity'
            iteration: Current iteration for tracking
        """
        if not isinstance(hint, dict) or "text" not in hint:
            logger.warning(f"Invalid hint format: {hint}")
            return
        
        text = hint.get("text", "").strip()
        if not text:
            return
        
        severity = hint.get("severity", "info")
        if severity not in self.VALID_SEVERITIES:
            severity = "info"
        
        # Check for duplicate (same text)
        for existing in hint_list:
            if existing.get("text", "").strip().lower() == text.lower():
                logger.debug(f"Duplicate hint skipped: {text[:50]}...")
                return
        
        # Add the hint
        new_hint = {
            "text": text,
            "severity": severity,
            "added_iteration": iteration
        }
        hint_list.append(new_hint)
        
        # Enforce max limit (drop oldest)
        while len(hint_list) > MAX_HINTS_PER_AGENT:
            dropped = hint_list.pop(0)
            logger.debug(f"Dropped oldest hint: {dropped.get('text', '')[:50]}...")
    
    def clear_hints(self):
        """Clear all hints and save empty state."""
        self._hints = self._empty_hints()
        self.save_hints()
        logger.info("Cleared all hints")
    
    def get_hints_for_agent(
        self,
        agent: str,
        role: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """
        Get hints for a specific agent.
        
        Args:
            agent: 'cypher_generator' or 'orchestrator'
            role: For orchestrator, the specific role ('generation', 'synthesis', etc.)
            
        Returns:
            List of hint dicts with 'text' and 'severity'
        """
        if agent == "cypher_generator":
            return self._hints.get("cypher_generator", [])
        elif agent == "orchestrator":
            if role and role in self.ORCHESTRATOR_ROLES:
                return self._hints.get("orchestrator", {}).get(role, [])
            else:
                # Return all orchestrator hints combined
                all_hints = []
                for r in self.ORCHESTRATOR_ROLES:
                    all_hints.extend(self._hints.get("orchestrator", {}).get(r, []))
                return all_hints
        else:
            logger.warning(f"Unknown agent: {agent}")
            return []
    
    def get_all_hints(self) -> Dict[str, Any]:
        """Return all hints."""
        return self._hints
    
    def has_hints(self) -> bool:
        """Check if there are any hints stored."""
        if self._hints.get("cypher_generator"):
            return True
        for role in self.ORCHESTRATOR_ROLES:
            if self._hints.get("orchestrator", {}).get(role):
                return True
        return False
    
    def format_hints_for_prompt(
        self,
        agent: str,
        role: Optional[str] = None,
        max_chars: int = 600
    ) -> str:
        """
        Format hints as a string for inclusion in prompts.
        
        Args:
            agent: 'cypher_generator' or 'orchestrator'
            role: For orchestrator, the specific role
            max_chars: Maximum characters for the formatted output
            
        Returns:
            Formatted string with hints, or empty string if no hints
        """
        hints = self.get_hints_for_agent(agent, role)
        
        if not hints:
            return ""
        
        lines = ["🧠 DEEP THINK GUIDANCE (from training analysis):"]
        
        # Severity icons
        icons = {
            "critical": "🔴 CRITICAL:",
            "warning": "⚠️ WARNING:",
            "info": "💡 TIP:"
        }
        
        # Sort by severity (critical first, then warning, then info)
        severity_order = {"critical": 0, "warning": 1, "info": 2}
        sorted_hints = sorted(hints, key=lambda h: severity_order.get(h.get("severity", "info"), 2))
        
        current_len = len(lines[0])
        for hint in sorted_hints:
            severity = hint.get("severity", "info")
            text = hint.get("text", "")
            icon = icons.get(severity, "💡 TIP:")
            
            line = f"  {icon} {text}"
            
            # Check if adding this line would exceed max_chars
            if current_len + len(line) + 1 > max_chars:
                lines.append("  ... (more hints truncated)")
                break
            
            lines.append(line)
            current_len += len(line) + 1
        
        return "\n".join(lines)
    
    def __repr__(self) -> str:
        """String representation."""
        cg_count = len(self._hints.get("cypher_generator", []))
        orch_counts = {
            role: len(self._hints.get("orchestrator", {}).get(role, []))
            for role in self.ORCHESTRATOR_ROLES
        }
        return f"PromptHintsManager(cypher={cg_count}, orchestrator={orch_counts})"


def load_hints_from_file(hints_file: str) -> Dict[str, Any]:
    """
    Convenience function to load hints from a file.
    
    Args:
        hints_file: Path to hints JSON file
        
    Returns:
        Hints dict or empty dict if file doesn't exist
    """
    manager = PromptHintsManager(hints_file)
    return manager.get_all_hints()


def save_hints_to_file(hints_file: str, hints: Dict[str, Any], iteration: int):
    """
    Convenience function to save hints to a file.
    
    Args:
        hints_file: Path to hints JSON file
        hints: Hints dict to save
        iteration: Current iteration number
    """
    manager = PromptHintsManager(hints_file)
    manager.add_hints(hints, iteration)

