#!/usr/bin/env python3
"""
Show the prompt generated by Cypher Generator Agent without running the model.

Usage:
    python show_prompt.py
    python show_prompt.py "Your custom question here"
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rl_implementation.agents import CypherGeneratorAgent


def main():
    # Get question from command line or use default
    if len(sys.argv) > 1:
        question = " ".join(sys.argv[1:])
    else:
        question = "What genes have physical interactions with INS?"
    
    print("=" * 80)
    print("CYPHER GENERATOR AGENT - PROMPT INSPECTOR")
    print("=" * 80)
    print(f"\nQuestion: {question}\n")
    
    # Initialize agent
    schema_path = "/nfs/turbo/umms-drjieliu/usr/rickyhan/rllm/examples/PanKLLM_RL_post-training/legacy/PankBaseAgent/schemas/kg_schema copy.json"
    agent = CypherGeneratorAgent(schema_path=schema_path, max_steps=5)
    agent.reset()
    
    # Get prompt for first step
    observation = {'question': question}
    agent.update_from_env(observation, reward=0.0, done=False, info={})
    
    messages = agent.chat_completions
    prompt = messages[0]['content']
    
    # Print statistics
    print("=" * 80)
    print("PROMPT STATISTICS:")
    print("=" * 80)
    print(f"Total characters: {len(prompt)}")
    print(f"Estimated tokens: ~{len(prompt)//4}")
    print(f"Lines: {len(prompt.splitlines())}")
    
    # Count sections
    sections = {
        "CRITICAL RULES": "CRITICAL RULES:" in prompt,
        "LEARNED PATTERNS": "LEARNED PATTERNS:" in prompt,
        "SCHEMA": "SCHEMA" in prompt,
        "QUESTION": "QUESTION:" in prompt,
    }
    
    print("\nSections present:")
    for section, present in sections.items():
        print(f"  {'✓' if present else '✗'} {section}")
    
    # Print the full prompt
    print("\n" + "=" * 80)
    print("FULL PROMPT:")
    print("=" * 80)
    print(prompt)
    print("=" * 80)
    
    # Show how to test with different questions
    print("\n💡 TIP: Test with different questions:")
    print('   python show_prompt.py "What SNPs are associated with Type 1 Diabetes?"')
    print('   python show_prompt.py "Find genes expressed in beta cells"')


if __name__ == "__main__":
    main()

