#!/usr/bin/env python3
"""
Display prompts generated by Orchestrator Agent for all four modes.

This script shows the actual prompts that would be sent to the LLM
for each of the Orchestrator's four roles.

Usage:
    python show_orchestrator_prompts.py
"""

import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from rl_implementation.agents import OrchestratorAgent


def show_all_prompts():
    """Display prompts for all four modes."""
    
    # Use the actual Pankbase schema
    schema_path = "/nfs/turbo/umms-drjieliu/usr/rickyhan/rllm/examples/PanKLLM_RL_post-training/legacy/PankBaseAgent/text_to_cypher/data/input/kg_schema.json"
    
    print("\n" + "=" * 80)
    print("ORCHESTRATOR AGENT - PROMPT EXAMPLES FOR ALL FOUR MODES")
    print("=" * 80 + "\n")
    print(f"Using schema: {schema_path}\n")
    
    agent = OrchestratorAgent(schema_path=schema_path)
    
    # ========================================================================
    # MODE 1: QUESTION GENERATION
    # ========================================================================
    print("=" * 80)
    print("MODE 1: QUESTION GENERATION")
    print("=" * 80)
    print("Purpose: Generate diverse training questions within scope")
    print("Token Budget: 1,800 tokens")
    print("=" * 80 + "\n")
    
    agent.set_mode('generation')
    agent.reset()
    
    observation = {
        'difficulty': 'medium',
        'curriculum_constraints': {
            'max_hops': 3,
            'focus_area': 'gene interactions and regulation'
        },
        'scope_constraints': {
            'allowed_node_types': ['gene', 'protein', 'snp'],
            'allowed_edge_types': ['physical_interaction', 'regulates'],
            'avoid_regions': [
                {'description': '[gene]-[:has_variant]->[variant] (returns inconsistent data)'}
            ]
        },
        'recent_questions': [
            'What genes interact with INS?',
            'Find proteins that bind to TP53',
            'Which genes regulate BRCA1 expression?'
        ]
    }
    
    agent.update_from_env(observation, 0.0, False, {})
    prompt = agent.chat_completions[0]['content']
    
    print(f"Prompt length: {len(prompt)} chars (~{len(prompt)//4} tokens)\n")
    print(prompt)
    print("\n")
    
    # ========================================================================
    # MODE 2: DATA QUALITY EVALUATION
    # ========================================================================
    print("=" * 80)
    print("MODE 2: DATA QUALITY EVALUATION")
    print("=" * 80)
    print("Purpose: Evaluate retrieved data and identify semantic ambiguities")
    print("Token Budget: 2,200 tokens")
    print("=" * 80 + "\n")
    
    agent.set_mode('data_eval')
    agent.reset()
    
    observation = {
        'question': 'What genes directly regulate INS expression?',
        'trajectory': [
            {
                'query': 'MATCH (g:gene)-[r:regulates]->(target:gene {name: "INS"}) RETURN g.name, r.evidence_type',
                'execution_time_ms': 180,
                'num_results': 47,
                'data_summary': 'Found 47 genes with regulates relationship. Evidence types include: direct transcription (5), co-expression (20), protein-protein interaction (15), pathway membership (7)'
            }
        ],
        'known_semantic_issues': [
            '⚠️ [associated_with]: Often indirect associations, not causal (confidence: 0.8)'
        ]
    }
    
    agent.update_from_env(observation, 0.0, False, {})
    prompt = agent.chat_completions[0]['content']
    
    print(f"Prompt length: {len(prompt)} chars (~{len(prompt)//4} tokens)\n")
    print(prompt)
    print("\n")
    
    # ========================================================================
    # MODE 3: ANSWER SYNTHESIS
    # ========================================================================
    print("=" * 80)
    print("MODE 3: ANSWER SYNTHESIS")
    print("=" * 80)
    print("Purpose: Convert KG data to natural language answer")
    print("Token Budget: 2,000 tokens")
    print("=" * 80 + "\n")
    
    agent.set_mode('synthesis')
    agent.reset()
    
    observation = {
        'question': 'What genes interact with INS?',
        'trajectory_data': [
            {
                'num_results': 23,
                'data_summary': 'Found 23 genes with physical interactions: GCG (glucagon, chr 2), IAPP (islet amyloid polypeptide, chr 12), SST (somatostatin, chr 3), and 20 others'
            },
            {
                'num_results': 23,
                'data_summary': 'Cell type expression: Beta cells (15 genes), alpha cells (12 genes), delta cells (8 genes)'
            }
        ],
        'data_quality_feedback': {
            'relevance_score': 0.9,
            'completeness_score': 0.85,
            'data_quality_score': 0.88
        }
    }
    
    agent.update_from_env(observation, 0.0, False, {})
    prompt = agent.chat_completions[0]['content']
    
    print(f"Prompt length: {len(prompt)} chars (~{len(prompt)//4} tokens)\n")
    print(prompt)
    print("\n")
    
    # ========================================================================
    # MODE 4: ANSWER QUALITY EVALUATION
    # ========================================================================
    print("=" * 80)
    print("MODE 4: ANSWER QUALITY EVALUATION")
    print("=" * 80)
    print("Purpose: Evaluate final answer quality")
    print("Token Budget: 1,500 tokens")
    print("=" * 80 + "\n")
    
    agent.set_mode('answer_eval')
    agent.reset()
    
    observation = {
        'question': 'What genes interact with INS?',
        'answer': 'Based on the knowledge graph, 23 genes have physical interactions with INS (insulin). The most notable interacting genes include GCG (glucagon, located on chromosome 2), IAPP (islet amyloid polypeptide, chromosome 12), and SST (somatostatin, chromosome 3). These genes are primarily expressed in pancreatic islet cells, with 15 genes expressed in beta cells, 12 in alpha cells, and 8 in delta cells. These interactions play important roles in glucose metabolism and hormone regulation, forming a complex regulatory network for insulin function.'
    }
    
    agent.update_from_env(observation, 0.0, False, {})
    prompt = agent.chat_completions[0]['content']
    
    print(f"Prompt length: {len(prompt)} chars (~{len(prompt)//4} tokens)\n")
    print(prompt)
    print("\n")
    
    # ========================================================================
    # SUMMARY
    # ========================================================================
    print("=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print("\nThe Orchestrator Agent generates different prompts for each role:")
    print("1. Question Generation: Generates training questions within scope")
    print("2. Data Quality Evaluation: Evaluates data and identifies semantic issues")
    print("3. Answer Synthesis: Converts data to natural language")
    print("4. Answer Quality Evaluation: Evaluates final answer")
    print("\nAll prompts stay within their token budgets and include relevant context.")
    print("\n✨ Prompt display complete!\n")


if __name__ == "__main__":
    show_all_prompts()

